variables:
  OMNIBUS_BRANCH: 'master'

image: gcc

build:
  stage: build
  script: make
  artifacts:
  paths:
    - fillit
  expire_in: 1 week

test_algo:
  stage: find
  script:
    - find . -name "fillit"
  stage: test
  script: ./fillit examples/valid_15
